=== AMWA-TV/nmos/discovery-registration/APIs/schemas/node.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes the Node and the services which run on it",
  "title": "Node resource",
  "required": [
    "id",
    "version",
    "label",
    "href",
    "caps",
    "services"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Node",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted PTP timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string"
    },
    "label": {
      "description": "Freeform string label for the Node",
      "type": "string"
    },
    "href": {
      "description": "HTTP access href for the Node's API",
      "type": "string"
    },
    "hostname": {
      "description": "Node hostname (optional)",
      "type": "string"
    },
    "caps": {
      "description": "Capabilities (not yet defined)",
      "type": "object"
    },
    "services": {
      "description": "Array of objects containing a URN format type and href",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["href", "type"],
        "properties": {
          "href": {
            "type": "string",
            "description": "URL to reach a service running on the Node"
          },
          "type": {
            "type": "string",
            "description": "URN identifying the type of service"
          }
        }
      }
    }
  }
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-nodeid-get-200.json
{
    "version": "1441716120:318744030", 
    "hostname": "host1", 
    "label": "host1", 
    "href": "http://172.29.176.102:12345/", 
    "services": [
        {
            "href": "http://172.29.176.102:12345/x-nmos/node/v1.0/self/status/", 
            "type": "urn:x-nmos:service:status"
        }, 
        {
            "href": "http://172.29.176.102:12345/x-nmos/node/v1.0/self/pipelinemanager/", 
            "type": "urn:x-nmos:service:pipelinemanager"
        }, 
        {
            "href": "http://172.29.176.102:12345/x-nmos/node/v1.0/self/mdnsbridge/", 
            "type": "urn:x-nmos:service:mdnsbridge"
        }
    ], 
    "caps": {}, 
    "id": "c8ba20e9-e197-4ec5-8764-4da672128589"
}

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-self-get-200.json
{
    "version": "1441700172:318426300", 
    "hostname": "host1", 
    "caps": {}, 
    "href": "http://172.29.80.65:12345/", 
    "services": [
        {
            "href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/pipelinemanager/", 
            "type": "urn:x-nmos:service:pipelinemanager"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/status/", 
            "type": "urn:x-nmos:service:status"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/tally/", 
            "type": "urn:x-nmos:service:tally"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/mdnsbridge/", 
            "type": "urn:x-nmos:service:mdnsbridge"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/storequery/", 
            "type": "urn:x-nmos:service:storequery"
        }
    ], 
    "label": "host1", 
    "id": "3b8be755-08ff-452b-b217-c9151eb21193"
}
