=== AMWA-TV/nmos/discovery-registration/APIs/schemas/receiver.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a receiver",
  "title": "Receiver resource",
  "required": [
    "id",
    "version",
    "label",
    "description",
    "format",
    "caps",
    "tags",
    "device_id",
    "transport",
    "subscription"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Receiver",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted PTP timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string"
    },
    "label": {
      "description": "Freeform string label for the Receiver",
      "type": "string"
    },
    "description": {
      "description": "Detailed description of the Receiver",
      "type": "string"
    },
    "format": {
      "description": "Type of Flow accepted by the Receiver as a URN",
      "type": "string",
      "enum": [
        "urn:x-nmos:format:video",
        "urn:x-nmos:format:audio",
        "urn:x-nmos:format:data"
      ]
    },
    "caps": {
      "description": "Capabilities (not yet defined)",
      "type": "object"
    },
    "tags": {
      "description": "Key value set of freeform string tags to aid in filtering sources. Values should be represented as an array of strings. Can be empty.",
      "type": "object"
    },
    "device_id": {
      "description": "Device ID which this Receiver forms part of",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "transport": {
      "description": "Transport type accepted by the Receiver in URN format",
      "type": "string",
      "enum": [
        "urn:x-nmos:transport:rtp",
        "urn:x-nmos:transport:rtp.ucast",
        "urn:x-nmos:transport:rtp.mcast",
        "urn:x-nmos:transport:dash"
      ]
    },
    "subscription": {
      "description": "Object containing the 'sender_id' currently subscribed to. Sender_id should be null on initialisation.",
      "type": "object",
      "properties": {
        "sender_id": {
          "type": "string",
          "description": "UUID of the Sender that this Receiver is currently subscribed to",
          "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
          "default": null
        }
      }
    }
  }
}

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-receiverid-get-200.json
{
    "description": "",
    "format": "urn:x-nmos:format:video",
    "tags": {},
    "caps": {},
    "subscription": {
        "sender_id": "2683ad14-642f-459d-a169-ef91c76cec6b"
    },
    "version": "1441704532:450093308",
    "label": "RTPRx",
    "id": "1eb53d65-ac83-441c-86f6-9b27df30ef0c",
    "transport": "urn:x-nmos:transport:rtp",
    "device_id": "05017e08-b329-45f9-a566-a3f99cc11e4d"
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-receiverid-get-200.json
{
    "description": "RTP Receiver", 
    "tags": {
        "Location": [
            "Location 1"
        ]
    }, 
    "format": "urn:x-nmos:format:video", 
    "caps": {}, 
    "device_id": "0d0cb97e-b96a-4a39-887f-d491492d9081", 
    "version": "1441895693:480000000", 
    "label": "Viewer", 
    "id": "3350d113-1593-4271-a7f5-f4974415bb8e", 
    "transport": "urn:x-nmos:transport:rtp", 
    "subscription": {
        "sender_id": "55311762-8003-48fa-a645-0a0c7621ce45"
    }
}
