=== AMWA-TV/nmos/discovery-registration/specifications/schemas/flow.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a Flow",
  "title": "Flow resource",
  "required": [
    "id",
    "version",
    "label",
    "description",
    "format",
    "tags",
    "source_id",
    "parents"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Flow",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted PTP timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string"
    },
    "label": {
      "description": "Freeform string label for the Flow",
      "type": "string"
    },
    "description": {
      "description": "Detailed description of the Flow",
      "type": "string"
    },
    "format": {
      "description": "Format of the data coming from the Flow as a URN",
      "type": "string",
      "enum": [
        "urn:x-nmos:format:video",
        "urn:x-nmos:format:audio",
        "urn:x-nmos:format:data"
      ]
    },
    "tags": {
      "description": "Key value set of freeform string tags to aid in filtering Flows. Values should be represented as an array of strings. Can be empty.",
      "type": "object"
    },
    "source_id": {
      "description": "Globally unique identifier for the Source which initially created the Flow",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "parents": {
      "description": "Array of UUIDs representing the Flow IDs of Grains which came together to generate this Flow (may change over the lifetime of this Flow)",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      }
    }
  }
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-flows-get-200.json
[
    {
        "description": "Off-air proxy", 
        "format": "urn:x-nmos:format:video", 
        "tags": {}, 
        "label": "Off-air proxy", 
        "version": "1441724130:194944510", 
        "parents": [],
        "source_id": "c7b1c809-84d4-427d-b6bb-c8397c66ce2b", 
        "id": "0c1f03d7-7e94-4b21-94d1-3ffbee8a0606"
    }, 
    {
        "description": "Off-air", 
        "format": "urn:x-nmos:format:video", 
        "tags": {}, 
        "label": "Off-air", 
        "version": "1441724130:186085940", 
        "parents": [],
        "source_id": "c7b1c809-84d4-427d-b6bb-c8397c66ce2b", 
        "id": "0e85d87b-4b19-4452-aea3-984c9f94bbc9"
    }, 
    {
        "description": "Capture Audio Proxy", 
        "format": "urn:x-nmos:format:audio", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "label": "Capture Audio Proxy", 
        "version": "1441812152:154331951", 
        "parents": [],
        "source_id": "2aa143ac-0ab7-4d75-bc32-5c00c13d186f", 
        "id": "b3bb5be7-9fe9-4324-a5bb-4c70e1084449"
    }
]

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-flowid-get-200.json
{
    "description": "Capture Audio Proxy", 
    "format": "urn:x-nmos:format:audio", 
    "tags": {
        "host": [
            "host1"
        ]
    }, 
    "label": "Capture Audio Proxy", 
    "version": "1441812152:154331951", 
    "parents": [],
    "source_id": "2aa143ac-0ab7-4d75-bc32-5c00c13d186f", 
    "id": "b3bb5be7-9fe9-4324-a5bb-4c70e1084449"
}

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-flows-get-200.json
[
    {
        "description": "Test Card", 
        "tags": {}, 
        "format": "urn:x-nmos:format:video", 
        "label": "Test Card", 
        "version": "1441704616:587121295", 
        "parents": [],
        "source_id": "02c46999-d532-4c52-905f-2e368a2af6cb", 
        "id": "5fbec3b1-1b0f-417d-9059-8b94a47197ed"
    },
    {
        "description": "VANC Data", 
        "tags": {}, 
        "format": "urn:x-nmos:format:data", 
        "label": "VANC Data", 
        "version": "1453880607:123995943", 
        "parents": [], 
        "source_id": "0e635152-e501-4d4e-bb87-9f3fe05eb79a", 
        "id": "db3bd465-2772-484f-8fac-830b0471258b"
    }
]
