=== AMWA-TV/nmos/discovery-registration/schemas/sender.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a sender",
  "title": "Sender resource",
  "required": [
    "id",
    "version",
    "label",
    "description",
    "flow_id",
    "transport",
    "device_id",
    "manifest_href"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Sender",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted PTP timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string"
    },
    "label": {
      "description": "Freeform string label for the Sender",
      "type": "string"
    },
    "description": {
      "description": "Detailed description of the Sender",
      "type": "string"
    },
    "flow_id": {
      "description": "ID of the Flow currently passing via this Sender",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "transport": {
      "description": "Transport type used by the Sender in URN format",
      "type": "string",
      "enum": [
        "urn:x-nmos:transport:rtp",
        "urn:x-nmos:transport:rtp.ucast",
        "urn:x-nmos:transport:rtp.mcast",
        "urn:x-nmos:transport:dash"
      ]
    },
    "tags": {
      "description": "Key value set of freeform string tags to aid in filtering Senders. Values should be represented as an array of strings. Can be empty.",
      "type": "object"
    },
    "device_id": {
      "description": "Device ID which this Sender forms part of",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "manifest_href": {
      "description": "HTTP URL to a file describing how to connect to the Sender (SDP for RTP)",
      "type": "string"
    }
  }
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-senderid-get-200.json
{
    "description": "Camera 1", 
    "label": "Camera 1", 
    "manifest_href": "http://172.29.176.146:12345/x-nmos/node/v1.0/self/pipelinemanager/run/pipeline/1/pipel/ipp_rtptxdfb1/misc/sdp/stream.sdp", 
    "version": "1441723958:235623703", 
    "flow_id": "b25d445a-20dc-4937-a8a1-5cb3d5c613ee", 
    "id": "171d5c80-7fff-4c23-9383-46503eb1c63e", 
    "transport": "urn:x-nmos:transport:rtp.mcast", 
    "device_id": "c501ae64-f525-48b7-9816-c5e8931bc017",
    "tags": {}
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-senders-get-200.json
[
    {
        "description": "Camera 1", 
        "label": "Camera 1", 
        "manifest_href": "http://172.29.80.25:12345/x-nmos/node/v1.0/self/pipelinemanager/run/pipeline/1/pipel/ipp_rtptx2701/misc/sdp/stream.sdp", 
        "version": "1441724086:828491206", 
        "flow_id": "75bfddce-7142-4368-bb4a-8a82c837c6df", 
        "id": "4002d6b5-5775-4975-9859-5b330fcea288", 
        "transport": "urn:x-nmos:transport:rtp.mcast", 
        "device_id": "3a98e804-9871-4699-ba31-d608309d8933",
        "tags": {}
    }, 
    {
        "description": "Camera 2", 
        "label": "Camera 2", 
        "manifest_href": "http://172.29.176.146:12345/x-nmos/node/v1.0/self/pipelinemanager/run/pipeline/1/pipel/ipp_rtptxdfb1/misc/sdp/stream.sdp", 
        "version": "1441723958:235623703", 
        "flow_id": "b25d445a-20dc-4937-a8a1-5cb3d5c613ee", 
        "id": "171d5c80-7fff-4c23-9383-46503eb1c63e", 
        "transport": "urn:x-nmos:transport:rtp.mcast", 
        "device_id": "c501ae64-f525-48b7-9816-c5e8931bc017",
        "tags": {}
    }, 
    {
        "description": "Camera 2 Audio", 
        "label": "Camera 2 Audio", 
        "manifest_href": "http://172.29.176.81:12345/x-nmos/node/v1.0/self/pipelinemanager/run/pipeline/1/pipel/ipp_rtptx10b7/misc/sdp/stream.sdp", 
        "version": "1441724039:737277493", 
        "flow_id": "4ffa5719-9ab9-4395-bedb-3534fa7ba438", 
        "id": "bb793530-8fd7-49f9-8514-314126bbc624", 
        "transport": "urn:x-nmos:transport:rtp.mcast", 
        "device_id": "5f88d383-596c-409c-887e-a90e42ef3684",
        "tags": {}
    }
]

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-senders-get-200.json
[
    {
        "description": "Test Card", 
        "label": "Test Card", 
        "version": "1441704616:890020555", 
        "manifest_href": "http://172.29.80.65:12345/x-nmos/node/v1.0/self/pipelinemanager/run/pipeline/3/pipel/ipp_rtptxfefa/misc/sdp/stream.sdp", 
        "flow_id": "5fbec3b1-1b0f-417d-9059-8b94a47197ed", 
        "id": "d7aa5a30-681d-4e72-92fb-f0ba0f6f4c3e", 
        "transport": "urn:x-nmos:transport:rtp.mcast", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5",
        "tags": {}
    }
]
