=== AMWA-TV/nmos/discovery-registration/schemas/source.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a Source",
  "title": "Source resource",
  "required": [
    "id",
    "version",
    "label",
    "description",
    "format",
    "caps",
    "tags",
    "device_id",
    "parents"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Source",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted PTP timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string"
    },
    "label": {
      "description": "Freeform string label for the Source",
      "type": "string"
    },
    "description": {
      "description": "Detailed description of the Source",
      "type": "string"
    },
    "format": {
      "description": "Format of the data coming from the Source as a URN",
      "type": "string",
      "enum": [
        "urn:x-nmos:format:video",
        "urn:x-nmos:format:audio",
        "urn:x-nmos:format:data"
      ]
    },
    "caps": {
      "description": "Capabilities (not yet defined)",
      "type": "object"
    },
    "tags": {
      "description": "Key value set of freeform string tags to aid in filtering Sources. Values should be represented as an array of strings. Can be empty.",
      "type": "object"
    },
    "device_id": {
      "description": "Globally unique identifier for the Device which initially created the Source",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "parents": {
      "description": "Array of UUIDs representing the Source IDs of Grains which came together at the input to this Source (may change over the lifetime of this Source)",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      }
    }
  }
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-sourceid-get-200.json
{
    "description": "Capture Card Source Video", 
    "format": "urn:x-nmos:format:video", 
    "tags": {
        "SourceDeviceType": [
            "HD Camera"
        ], 
        "host": [
            "host1"
        ], 
        "Location": [
            "Location 1"
        ]
    }, 
    "caps": {}, 
    "version": "1441722516:851371645", 
    "parents": [], 
    "label": "CaptureCardSourceVideo", 
    "id": "c23c6a65-8e91-4f6c-a484-046363dbca29", 
    "device_id": "65fa8c20-890e-4b86-87b2-cfd9df91b7f8"
}

=== AMWA-TV/nmos/discovery-registration/examples/queryapi-v1.0-sources-get-200.json
[
    {
        "description": "Camera 1", 
        "format": "urn:x-nmos:format:video", 
        "tags": {
            "SourceDeviceType": [
                "UHD Camera"
            ], 
            "host": [
                "host1"
            ], 
            "location": [
                "Location 1"
            ]
        }, 
        "caps": {}, 
        "version": "1441724551:288670563", 
        "parents": [], 
        "label": "Camera 1", 
        "id": "042a4126-0208-443d-bda6-833ffc27ed51", 
        "device_id": "21a28338-fb2e-4df5-9b55-d58e6124bc9f"
    }, 
    {
        "description": "Camera 2", 
        "format": "urn:x-nmos:format:video", 
        "tags": {
            "SourceDeviceType": [
                "HD Camera"
            ], 
            "host": [
                "host2"
            ], 
            "Location": [
                "Location 2"
            ]
        }, 
        "caps": {}, 
        "version": "1441722516:851371645", 
        "parents": [], 
        "label": "CaptureCardSourceVideo", 
        "id": "c23c6a65-8e91-4f6c-a484-046363dbca29", 
        "device_id": "65fa8c20-890e-4b86-87b2-cfd9df91b7f8"
    }, 
    {
        "description": "Audio 1", 
        "format": "urn:x-nmos:format:audio", 
        "tags": {
            "host": [
                "host3"
            ]
        }, 
        "caps": {}, 
        "version": "1441719058:3226205", 
        "parents": [], 
        "label": "Audio 1", 
        "id": "62cf8dd3-015b-49e3-84c1-1d866a7540bc", 
        "device_id": "e7aa15c4-f793-4d43-a0cb-c638db6215ac"
    }
]

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-sources-get-200.json
[
    {
        "description": "Capture Card Source Video", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "format": "urn:x-nmos:format:video", 
        "caps": {}, 
        "version": "1441703336:902850419", 
        "parents": [], 
        "label": "CaptureCardSourceVideo", 
        "id": "4569cea2-ab63-4f97-8dd1-bad4669ea5e4", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
    }, 
    {
        "description": "Capture Card Source Audio", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "format": "urn:x-nmos:format:audio", 
        "caps": {}, 
        "version": "1441703336:912670314", 
        "parents": [], 
        "label": "CaptureCardSourceAudio", 
        "id": "fc97ab0f-b51b-4129-9385-dcaf30f9482b", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
    }, 
    {
        "description": "Capture Card Source Audio", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "format": "urn:x-nmos:format:audio", 
        "caps": {}, 
        "version": "1441704614:174935325", 
        "parents": [], 
        "label": "CaptureCardSourceAudio", 
        "id": "9738780e-141f-4e19-8601-a157dc855aa2", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
    }, 
    {
        "description": "Capture Card Source Video", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "format": "urn:x-nmos:format:video", 
        "caps": {}, 
        "version": "1441704614:163285887", 
        "parents": [], 
        "label": "CaptureCardSourceVideo", 
        "id": "02c46999-d532-4c52-905f-2e368a2af6cb", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
    },
    {
        "description": "Capture Card Source VANC", 
        "tags": {
            "host": [
                "host1"
            ]
        }, 
        "format": "urn:x-nmos:format:data", 
        "caps": {}, 
        "version": "1453880605:374934072", 
        "parents": [], 
        "label": "Capture Card Source VANC", 
        "id": "0e635152-e501-4d4e-bb87-9f3fe05eb79a", 
        "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
    }
]

=== AMWA-TV/nmos/discovery-registration/examples/nodeapi-v1.0-sourceid-get-200.json
{
    "description": "Capture Card Source Video",
    "tags": {
        "host": [
            "host1"
        ]
    },
    "format": "urn:x-nmos:format:video",
    "caps": {},
    "version": "1441703336:902850419",
    "parents": [],
    "label": "CaptureCardSourceVideo",
    "id": "4569cea2-ab63-4f97-8dd1-bad4669ea5e4",
    "device_id": "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5"
}
